(()=>{
'use strict';
const root=document.getElementById('canvas');const c=document.createElement('canvas');c.id='gameCanvas';root.replaceChildren(c);const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;
const W=1200,H=760;let state='menu',last=0,wave=1,gold=500,xp=0,level=1,nextXp=100,side=0,spawned=0,spawnTimer=.5,notice='',noticeTime=0,heroType='warrior',shopOpen=false;
const keys=new Set(),enemies=[],shots=[],fx=[],books={str:0,agi:0,int:0},inventory=[];
const data={warrior:{name:'전사',hp:560,speed:245,damage:48,range:115,rate:.34,skill:7},mage:{name:'마법사',hp:340,speed:225,damage:62,range:205,rate:.55,skill:6},ranger:{name:'궁수',hp:400,speed:280,damage:40,range:250,rate:.22,skill:8}};
const hero={x:600,y:595,hp:560,maxHp:560,speed:245,damage:48,range:115,rate:.34,attack:0,skill:0,crit:.08,power:1,lifesteal:0};
const tower={x:600,y:380,hp:3200,maxHp:3200,armor:0};
const sides=[{x:600,y:45,n:'북'},{x:1155,y:380,n:'동'},{x:600,y:715,n:'남'},{x:45,y:380,n:'서'}];
const types={grunt:{hp:75,spd:58,dmg:13,gold:10,xp:14,r:13},runner:{hp:48,spd:112,dmg:9,gold:12,xp:18,r:10},tank:{hp:270,spd:36,dmg:30,gold:25,xp:42,r:20},caster:{hp:100,spd:48,dmg:26,gold:18,xp:30,r:14},boss:{hp:2800,spd:27,dmg:75,gold:400,xp:560,r:34}};
const items=[['강철검','공격력 +35',180,()=>hero.damage+=35],['질주화','이동속도 +55',220,()=>hero.speed+=55],['수호갑옷','최대 HP +180',260,()=>{hero.maxHp+=180;hero.hp+=180}],['흡혈부적','타격 시 HP +3',320,()=>hero.lifesteal+=3],['마력핵','Q 피해 +60%',360,()=>hero.power+=.6],['용사의 반지','공격력 +20 / 치명타 +8%',420,()=>{hero.damage+=20;hero.crit+=.08}]];
function resize(){const r=root.getBoundingClientRect();const s=Math.min(r.width/W,r.height/H)||1;c.width=W;c.height=H;c.style.width=W*s+'px';c.style.height=H*s+'px'}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if(k==='q')useSkill();if(k==='i')toggleShop();if(k==='escape'){if(state==='play'){state='pause';document.getElementById('pause').classList.remove('hidden')}else if(state==='pause'){resume()}else if(state==='shop'){toggleShop()}}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function hide(id){document.getElementById(id).classList.add('hidden')}function show(id){document.getElementById(id).classList.remove('hidden')}
function chooseHero(type){heroType=type;const d=data[type];Object.assign(hero,{x:600,y:595,maxHp:d.hp,hp:d.hp,speed:d.speed,damage:d.damage,range:d.range,rate:d.rate,attack:0,skill:0,crit:type==='ranger'?.16:.08,power:1,lifesteal:0});wave=1;gold=500;xp=0;level=1;nextXp=100;side=0;spawned=0;spawnTimer=.3;enemies.length=0;shots.length=0;fx.length=0;inventory.length=0;books.str=books.agi=books.int=0;tower.hp=tower.maxHp;shopOpen=false;state='play';hide('heroSelect');hide('start');hide('gameover');hide('pause');hide('levelUp');hide('shop');say('웨이브 1 시작',2)}
function say(t,tim){notice=t;noticeTime=tim}
function need(){return 8+wave*2+Math.floor(wave/3)}
function spawn(){if(spawned>=need())return;let kind='grunt',r=Math.random();if(wave%5===0&&spawned===need()-1)kind='boss';else if(r<.14)kind='runner';else if(r<.3)kind='tank';else if(r<.4)kind='caster';const g=types[kind],s=sides[side],x=s.x+(Math.random()-.5)*48,y=s.y+(Math.random()-.5)*48,scale=1+wave*.12;enemies.push({kind,x,y,hp:g.hp*scale,max:g.hp*scale,spd:g.spd*(1+wave*.01),dmg:g.dmg*(1+wave*.055),r:g.r,hit:0,dead:false});spawned++;spawnTimer=Math.max(.18,.48-wave*.005)}
function addXp(v){xp+=v;while(xp>=nextXp){xp-=nextXp;level++;nextXp=Math.floor(nextXp*1.28);openLevel()}}
function openLevel(){state='level';const box=document.getElementById('levelChoices');box.replaceChildren();[['공격력 +22',()=>hero.damage+=22],['최대 HP +120',()=>{hero.maxHp+=120;hero.hp+=120}],['이동속도 +32',()=>hero.speed+=32]].forEach(([txt,fn])=>{const b=document.createElement('button');b.className='upgradeChoice';b.textContent=txt;b.onclick=()=>{fn();hide('levelUp');state='play';say('성장 완료',1)};box.appendChild(b)});show('levelUp')}
function kill(e){if(e.dead)return;e.dead=true;const d=types[e.kind];gold+=d.gold;addXp(d.xp);burst(e.x,e.y,e.kind==='boss'?'#edbd54':'#dde8d8',e.kind==='boss'?35:10)}
function burst(x,y,col,n){for(let i=0;i<n;i++)fx.push({x,y,vx:(Math.random()-.5)*200,vy:(Math.random()-.5)*200,life:.5,col})}
function hurt(e,dmg){e.hp-=dmg;if(e.hp<=0)kill(e);burst(e.x,e.y,'#f0d68b',3)}
function move(dt){let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(dx||dy){const n=Math.hypot(dx,dy);hero.x=Math.max(65,Math.min(W-65,hero.x+dx/n*hero.speed*dt));hero.y=Math.max(65,Math.min(H-65,hero.y+dy/n*hero.speed*dt))}}
function attack(){if(hero.attack>0)return;let t=null,dist=hero.range;for(const e of enemies)if(!e.dead){const d=Math.hypot(e.x-hero.x,e.y-hero.y);if(d<dist){dist=d;t=e}}if(!t)return;hero.attack=hero.rate;const dmg=hero.damage*(Math.random()<hero.crit?2:1);if(heroType==='warrior'){hurt(t,dmg)}else{shots.push({x:hero.x,y:hero.y,target:t,dmg,life:.45,type:heroType})}if(hero.lifesteal)hero.hp=Math.min(hero.maxHp,hero.hp+hero.lifesteal)}
function updateShots(dt){for(const s of shots){if(s.life<=0)continue;const t=s.target;if(!t||t.dead){s.life=0;continue}s.life-=dt;s.x+=(t.x-s.x)*Math.min(1,dt*12);s.y+=(t.y-s.y)*Math.min(1,dt*12);if(Math.hypot(t.x-s.x,t.y-s.y)<18){hurt(t,s.dmg);if(s.type==='ranger'&&Math.random()<.3){for(const e of enemies){if(!e.dead&&e!==t&&Math.hypot(e.x-t.x,e.y-t.y)<90){hurt(e,s.dmg*.55);break}}}s.life=0}}for(let i=shots.length-1;i>=0;i--)if(shots[i].life<=0)shots.splice(i,1)}
function useSkill(){if(state!=='play'||hero.skill>0)return;hero.skill=data[heroType].skill;const rad=heroType==='warrior'?175:220,mult=heroType==='warrior'?5:4;for(const e of enemies)if(!e.dead&&Math.hypot(e.x-hero.x,e.y-hero.y)<rad)hurt(e,hero.damage*mult*hero.power);burst(hero.x,hero.y,heroType==='mage'?'#7ad9ee':heroType==='ranger'?'#9bda79':'#efb84f',45);say('필살기 발동',1)}
function update(dt){if(state!=='play')return;hero.attack=Math.max(0,hero.attack-dt);hero.skill=Math.max(0,hero.skill-dt);move(dt);attack();spawnTimer-=dt;if(spawnTimer<=0)spawn();updateShots(dt);let alive=0;for(const e of enemies)if(!e.dead){alive++;e.hit=Math.max(0,e.hit-dt);const dx=tower.x-e.x,dy=tower.y-e.y,d=Math.hypot(dx,dy)||1;if(d<94){tower.hp-=Math.max(1,e.dmg-tower.armor)*dt;if(e.hit<=0){e.hit=.7;burst(e.x,e.y,'#b5575d',5)}}else{e.x+=dx/d*e.spd*dt;e.y+=dy/d*e.spd*dt}}for(const p of fx){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.9;p.vy*=.9;p.life-=dt}for(let i=fx.length-1;i>=0;i--)if(fx[i].life<=0)fx.splice(i,1);for(let i=enemies.length-1;i>=0;i--)if(enemies[i].dead)enemies.splice(i,1);if(spawned>=need()&&alive===0){side=(side+1)%4;spawned=0;spawnTimer=.4;if(side===0){wave++;gold+=100;tower.hp=Math.min(tower.maxHp,tower.hp+150);say('웨이브 '+wave,2.2)}else say(sides[side].n+' 방향 적습',1.2)}if(tower.hp<=0){tower.hp=0;state='over';document.getElementById('overDetail').textContent=`웨이브 ${wave} · 레벨 ${level} · ${gold} G · ${data[heroType].name}`;show('gameover')}}
function buy(i){const it=items[i];if(gold<it[2])return;say(it[0]+' 구매',1);gold-=it[2];it[3]();inventory.push(it[0]);renderShop()}
function buyBook(type){const cost=100+books[type]*50;if(gold<cost)return;gold-=cost;books[type]++;if(type==='str')hero.damage+=8;if(type==='agi')hero.speed+=10;if(type==='int')hero.power+=.08;say((type==='str'?'힘':type==='agi'?'민첩':'지능')+' 책 사용',1);renderShop()}
function renderShop(){document.getElementById('shopGold').textContent=gold+' G';const box=document.getElementById('shopItems');box.replaceChildren();items.forEach((it,i)=>{const b=document.createElement('button');b.className='shopItem';b.innerHTML='<strong>'+it[0]+'</strong><span>'+it[1]+'</span><em>'+it[2]+' G</em>';b.onclick=()=>buy(i);box.appendChild(b)});const booksBox=document.getElementById('bookLine');booksBox.replaceChildren();[['str','힘'],['agi','민첩'],['int','지능']].forEach(([k,n])=>{const b=document.createElement('button');b.className='bookBtn';b.textContent=n+' 책 · '+(100+books[k]*50)+'G';b.onclick=()=>buyBook(k);booksBox.appendChild(b)})}
function toggleShop(){if(state==='menu'||state==='over'||state==='level')return;shopOpen=!shopOpen;state=shopOpen?'shop':'play';document.getElementById('shop').classList.toggle('hidden',!shopOpen);if(shopOpen)renderShop()}
function resume(){hide('pause');state='play'}function menu(){state='menu';hide('gameover');hide('pause');hide('levelUp');hide('shop');show('start')}
function draw(){ctx.fillStyle='#17241d';ctx.fillRect(0,0,W,H);for(let y=0;y<H;y+=32)for(let x=0;x<W;x+=32){ctx.fillStyle=((x/32+y/32)&1)?'#1b2b22':'#203228';ctx.fillRect(x,y,32,32)}ctx.fillStyle='#2a402f';ctx.fillRect(160,110,880,540);ctx.fillStyle='#314b38';ctx.fillRect(555,110,90,540);ctx.fillRect(160,335,880,90);for(const s of sides){ctx.fillStyle='#536b54';ctx.fillRect(s.x-32,s.y-20,64,40);ctx.fillStyle='#9bb58e';ctx.fillRect(s.x-20,s.y-10,40,20);ctx.fillStyle='#172019';ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText(s.n,s.x,s.y+4);ctx.textAlign='left'}drawTower();for(const e of enemies)drawEnemy(e);for(const s of shots)drawShot(s);drawHero();for(const p of fx){ctx.globalAlpha=Math.max(0,p.life/.5);ctx.fillStyle=p.col;ctx.fillRect(p.x|0,p.y|0,6,6);ctx.globalAlpha=1}drawHud();if(noticeTime>0){ctx.fillStyle='#0b1310';ctx.fillRect(420,126,360,38);ctx.fillStyle='#e9c66c';ctx.font='bold 17px monospace';ctx.textAlign='center';ctx.fillText(notice,600,151);ctx.textAlign='left';noticeTime-=1/60}}
function drawTower(){ctx.fillStyle='#0b120e';ctx.fillRect(505,478,190,28);ctx.fillStyle='#60745f';ctx.fillRect(520,290,160,188);ctx.fillStyle='#35493a';ctx.fillRect(548,318,104,160);ctx.fillStyle='#789078';ctx.fillRect(525,270,40,64);ctx.fillRect(635,270,40,64);ctx.fillStyle='#7f5945';ctx.beginPath();ctx.moveTo(500,290);ctx.lineTo(600,220);ctx.lineTo(700,290);ctx.fill();ctx.fillStyle='#51d5d5';ctx.fillRect(576,376,48,102);bar(480,198,240,15,tower.hp/tower.maxHp,'#251616','#63d68a');ctx.fillStyle='#efe4bc';ctx.font='bold 16px monospace';ctx.textAlign='center';ctx.fillText('중앙 수호탑',600,186);ctx.textAlign='left')}
function drawHero(){ctx.save();ctx.translate(hero.x,hero.y);ctx.fillStyle='#0e1511';ctx.fillRect(-18,24,36,7);ctx.fillStyle='#e0bd99';ctx.fillRect(-11,-27,22,21);ctx.fillStyle=heroType==='warrior'?'#c98a48':heroType==='mage'?'#75a8df':'#7dbb75';ctx.fillRect(-15,-6,30,29);ctx.fillStyle='#222d28';ctx.fillRect(-11,16,9,13);ctx.fillRect(2,16,9,13);if(heroType==='warrior'){ctx.fillStyle='#dcd1bc';ctx.fillRect(17,-10,6,38)}else if(heroType==='mage'){ctx.fillStyle='#d9bd69';ctx.fillRect(18,-30,5,51);ctx.fillStyle='#72d9ed';ctx.fillRect(13,-34,15,6)}else{ctx.strokeStyle='#b9783e';ctx.lineWidth=4;ctx.beginPath();ctx.arc(19,0,17,-1.7,1.7);ctx.stroke()}ctx.restore()}
function drawEnemy(e){const d=types[e.kind],col=e.kind==='boss'?'#b73e4c':e.kind==='tank'?'#728568':e.kind==='caster'?'#8064ae':e.kind==='runner'?'#b7aa58':'#9b755b';ctx.fillStyle=col;ctx.fillRect(e.x-d.r,e.y-d.r,d.r*2,d.r*2);ctx.fillStyle='#271812';ctx.fillRect(e.x-d.r*.5,e.y-d.r*.2,5,5);ctx.fillRect(e.x+d.r*.2,e.y-d.r*.2,5,5);bar(e.x-d.r,e.y-d.r-9,d.r*2,5,e.hp/e.maxHp,'#2a1717','#d85f62')}
function drawShot(s){ctx.fillStyle=s.type==='mage'?'#70dced':'#ead27e';ctx.fillRect(s.x|0,s.y|0,s.type==='mage'?8:6,4)}
function drawHud(){ctx.fillStyle='#0a110d';ctx.fillRect(14,14,360,112);ctx.fillStyle='#f0d078';ctx.font='bold 20px monospace';ctx.fillText('WAVE '+wave,28,40);ctx.fillStyle='#d4e0d9';ctx.font='13px monospace';ctx.fillText(sides[side].n+' 방향 · '+spawned+'/'+need()+' 처치 예정',28,63);ctx.fillText('LV '+level+' · XP '+xp+'/'+nextXp,28,84);ctx.fillText('GOLD '+gold+' · [I] 상점 · [Q] 스킬',28,105);ctx.fillStyle='#0a110d';ctx.fillRect(900,14,286,112);ctx.fillStyle='#d9eee3';ctx.fillText('수호탑 HP',916,38);bar(916,47,250,14,tower.hp/tower.maxHp,'#281616','#63d68a');ctx.fillText('영웅 HP '+Math.ceil(hero.hp)+'/'+hero.maxHp,916,78);bar(916,87,250,12,hero.hp/hero.maxHp,'#281616','#4c9fe0');ctx.fillText('Q '+(hero.skill>0?hero.skill.toFixed(1)+'s':'READY')+' · '+data[heroType].name,916,114)}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}
document.getElementById('startBtn').onclick=()=>{hide('start');show('heroSelect')};document.getElementById('warriorBtn').onclick=()=>chooseHero('warrior');document.getElementById('mageBtn').onclick=()=>chooseHero('mage');document.getElementById('rangerBtn').onclick=()=>chooseHero('ranger');document.getElementById('restartBtn').onclick=menu;document.getElementById('resumeBtn').onclick=resume;document.getElementById('shopClose').onclick=toggleShop;hide('heroSelect');hide('levelUp');hide('shop');hide('pause');hide('gameover');show('start');requestAnimationFrame(loop);
})();