(()=>{
'use strict';
const root=document.getElementById('canvas'),c=document.createElement('canvas'),ctx=c.getContext('2d');c.id='gameCanvas';root.replaceChildren(c);ctx.imageSmoothingEnabled=false;
const W=1200,H=760;let state='menu',last=0,wave=1,gold=500,xp=0,level=1,nextXp=100,side=0,spawned=0,timer=.4,notice='',noticeT=0,type='warrior';
const keys=new Set(),enemies=[],shots=[],fx=[],book={str:0,agi:0,int:0};
const hero={x:600,y:595,hp:560,maxHp:560,speed:245,damage:48,range:115,rate:.34,attack:0,skill:0,crit:.08,power:1,lifesteal:0};
const H={warrior:['전사',560,245,48,115,.34,7,'#c98a48'],mage:['마법사',340,225,62,205,.55,6,'#75a8df'],ranger:['궁수',400,280,40,250,.22,8,'#7dbb75']};
const T={grunt:[75,58,13,10,14,13],runner:[48,112,9,12,18,10],tank:[270,36,30,25,42,20],caster:[100,48,26,18,30,14],boss:[2800,27,75,400,560,34]};
const gates=[['북',600,45],['동',1155,380],['남',600,715],['서',45,380]];
const items=[['강철검','공격력 +35',180,()=>hero.damage+=35],['질주화','이동속도 +55',220,()=>hero.speed+=55],['수호갑옷','최대 HP +180',260,()=>{hero.maxHp+=180;hero.hp+=180}],['흡혈부적','타격 회복 +3',320,()=>hero.lifesteal+=3],['마력핵','Q 피해 +60%',360,()=>hero.power+=.6],['용사의 반지','공격력 +20 / 치명 +8%',420,()=>{hero.damage+=20;hero.crit+=.08}]];
function resize(){let r=root.getBoundingClientRect(),s=Math.min(r.width/W,r.height/H)||1;c.width=W;c.height=H;c.style.width=W*s+'px';c.style.height=H*s+'px'}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{let k=e.key.toLowerCase();keys.add(k);if(k==='q')skill();if(k==='i')shop();if(k==='escape'){if(state==='play'){state='pause';show('pause')}else if(state==='pause'){state='play';hide('pause')}else if(state==='shop'){shop()}}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function show(id){document.getElementById(id).classList.remove('hidden')}function hide(id){document.getElementById(id).classList.add('hidden')}
function start(t){type=t;let d=H[t];Object.assign(hero,{x:600,y:595,maxHp:d[1],hp:d[1],speed:d[2],damage:d[3],range:d[4],rate:d[5],skill:0,crit:t==='ranger'?.16:.08,power:1,lifesteal:0,attack:0});wave=1;gold=500;xp=0;level=1;nextXp=100;side=0;spawned=0;timer=.3;enemies.length=0;shots.length=0;fx.length=0;book.str=book.agi=book.int=0;state='play';['start','heroSelect','levelUp','shop','pause','gameover'].forEach(hide);say('웨이브 1 시작',2)}
function say(s,t){notice=s;noticeT=t}
function count(){return 8+wave*2+Math.floor(wave/3)}
function spawn(){if(spawned>=count())return;let k='grunt',r=Math.random();if(wave%5===0&&spawned===count()-1)k='boss';else if(r<.14)k='runner';else if(r<.30)k='tank';else if(r<.40)k='caster';let d=T[k],g=gates[side],sc=1+wave*.12;enemies.push({k,x:g[1]+(Math.random()-.5)*50,y:g[2]+(Math.random()-.5)*50,hp:d[0]*sc,max:d[0]*sc,spd:d[1]*(1+wave*.01),dmg:d[2]*(1+wave*.05),r:d[5],dead:false});spawned++;timer=Math.max(.18,.46-wave*.005)}
function kill(e){if(e.dead)return;e.dead=true;let d=T[e.k];gold+=d[3];gain(d[4]);burst(e.x,e.y,e.k==='boss'?'#eab94e':'#dbe7db',e.k==='boss'?32:9)}
function gain(n){xp+=n;while(xp>=nextXp){xp-=nextXp;level++;nextXp=Math.floor(nextXp*1.28);levelUp()}}
function levelUp(){state='level';let box=document.getElementById('levelChoices');box.replaceChildren();[['공격력 +22',()=>hero.damage+=22],['최대 HP +120',()=>{hero.maxHp+=120;hero.hp+=120}],['이동속도 +32',()=>hero.speed+=32]].forEach(a=>{let b=document.createElement('button');b.className='upgradeChoice';b.textContent=a[0];b.onclick=()=>{a[1]();hide('levelUp');state='play'};box.appendChild(b)});show('levelUp')}
function move(dt){let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(dx||dy){let n=Math.hypot(dx,dy);hero.x=Math.max(70,Math.min(1130,hero.x+dx/n*hero.speed*dt));hero.y=Math.max(70,Math.min(690,hero.y+dy/n*hero.speed*dt))}}
function hit(e,d){e.hp-=d;if(e.hp<=0)kill(e);burst(e.x,e.y,'#f2d68d',2)}
function attack(){if(hero.attack>0)return;let target=null,best=hero.range;for(let e of enemies)if(!e.dead){let d=Math.hypot(e.x-hero.x,e.y-hero.y);if(d<best){best=d;target=e}}if(!target)return;hero.attack=hero.rate;let d=hero.damage*(Math.random()<hero.crit?2:1);if(type==='warrior')hit(target,d);else shots.push({x:hero.x,y:hero.y,t:target,d,life:.5});if(hero.lifesteal)hero.hp=Math.min(hero.maxHp,hero.hp+hero.lifesteal)}
function skill(){if(state!=='play'||hero.skill>0)return;hero.skill=H[type][6];let rad=type==='warrior'?180:230,m=type==='warrior'?5:4;for(let e of enemies)if(!e.dead&&Math.hypot(e.x-hero.x,e.y-hero.y)<rad)hit(e,hero.damage*m*hero.power);burst(hero.x,hero.y,type==='mage'?'#70dbef':type==='ranger'?'#91d774':'#efb94c',42);say('필살기!',1)}
function updateShots(dt){for(let s of shots){if(!s.t||s.t.dead){s.life=0;continue}s.life-=dt;s.x+=(s.t.x-s.x)*Math.min(1,dt*14);s.y+=(s.t.y-s.y)*Math.min(1,dt*14);if(Math.hypot(s.t.x-s.x,s.t.y-s.y)<18){hit(s.t,s.d);if(type==='ranger'&&Math.random()<.3)for(let e of enemies)if(!e.dead&&e!==s.t&&Math.hypot(e.x-s.t.x,e.y-s.t.y)<90){hit(e,s.d*.5);break}s.life=0}}for(let i=shots.length-1;i>=0;i--)if(shots[i].life<=0)shots.splice(i,1)}
function update(dt){if(state!=='play')return;hero.attack=Math.max(0,hero.attack-dt);hero.skill=Math.max(0,hero.skill-dt);move(dt);attack();timer-=dt;if(timer<=0)spawn();updateShots(dt);let alive=0;for(let e of enemies)if(!e.dead){alive++;let dx=tower.x-e.x,dy=tower.y-e.y,d=Math.hypot(dx,dy)||1;if(d<92)tower.hp-=Math.max(1,e.dmg-tower.armor)*dt;else{e.x+=dx/d*e.spd*dt;e.y+=dy/d*e.spd*dt}}for(let p of fx){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.9;p.vy*=.9;p.life-=dt}for(let i=fx.length-1;i>=0;i--)if(fx[i].life<=0)fx.splice(i,1);for(let i=enemies.length-1;i>=0;i--)if(enemies[i].dead)enemies.splice(i,1);if(spawned>=count()&&alive===0){side=(side+1)%4;spawned=0;timer=.5;if(side===0){wave++;gold+=100;tower.hp=Math.min(tower.maxHp,tower.hp+150);say('웨이브 '+wave,2)}else say(gates[side][0]+' 방향 적습',1.2)}if(tower.hp<=0){tower.hp=0;state='over';document.getElementById('overDetail').textContent=`웨이브 ${wave} · 레벨 ${level} · ${gold} G · ${H[type][0]}`;show('gameover')}}
const tower={x:600,y:380,hp:3200,maxHp:3200,armor:0};
function burst(x,y,col,n){for(let i=0;i<n;i++)fx.push({x,y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.5,col})}
function shop(){if(state==='menu'||state==='over'||state==='level')return;shopOpen=!shopOpen;state=shopOpen?'shop':'play';document.getElementById('shop').classList.toggle('hidden',!shopOpen);if(shopOpen)renderShop()}let shopOpen=false;
function buy(i){let a=items[i];if(gold<a[2])return;gold-=a[2];a[3]();say(a[0]+' 구매',1);renderShop()}
function bookBuy(k){let cost=100+book[k]*50;if(gold<cost)return;gold-=cost;book[k]++;if(k==='str')hero.damage+=8;if(k==='agi')hero.speed+=10;if(k==='int')hero.power+=.08;renderShop()}
function renderShop(){document.getElementById('shopGold').textContent=gold+' G';let box=document.getElementById('shopItems');box.replaceChildren();items.forEach((a,i)=>{let b=document.createElement('button');b.className='shopItem';b.innerHTML='<strong>'+a[0]+'</strong><span>'+a[1]+'</span><em>'+a[2]+' G</em>';b.onclick=()=>buy(i);box.appendChild(b)});let bb=document.getElementById('bookLine');bb.replaceChildren();[['str','힘'],['agi','민첩'],['int','지능']].forEach(a=>{let b=document.createElement('button');b.className='bookBtn';b.textContent=a[1]+' 책 · '+(100+book[a[0]]*50)+'G';b.onclick=()=>bookBuy(a[0]);bb.appendChild(b)})}
function menu(){state='menu';['heroSelect','levelUp','shop','pause','gameover'].forEach(hide);show('start')}
function draw(){ctx.fillStyle='#17251d';ctx.fillRect(0,0,W,H);for(let y=0;y<H;y+=32)for(let x=0;x<W;x+=32){ctx.fillStyle=((x/32+y/32)&1)?'#1c2c23':'#203328';ctx.fillRect(x,y,32,32)}ctx.fillStyle='#2c4332';ctx.fillRect(160,110,880,540);ctx.fillStyle='#304a36';ctx.fillRect(555,110,90,540);ctx.fillRect(160,335,880,90);for(let g of gates){ctx.fillStyle='#60765f';ctx.fillRect(g[1]-32,g[2]-20,64,40);ctx.fillStyle='#9eb99a';ctx.fillRect(g[1]-20,g[2]-10,40,20)}drawTower();for(let e of enemies)drawEnemy(e);for(let s of shots)drawShot(s);drawHero();for(let p of fx){ctx.globalAlpha=Math.max(0,p.life/.5);ctx.fillStyle=p.col;ctx.fillRect(p.x|0,p.y|0,6,6);ctx.globalAlpha=1}drawHud();if(noticeT>0){ctx.fillStyle='#0a120e';ctx.fillRect(430,128,340,38);ctx.fillStyle='#edc66a';ctx.font='bold 17px monospace';ctx.textAlign='center';ctx.fillText(notice,600,153);ctx.textAlign='left';noticeT-=1/60}}
function drawTower(){ctx.fillStyle='#0b130e';ctx.fillRect(500,480,200,28);ctx.fillStyle='#627661';ctx.fillRect(520,292,160,188);ctx.fillStyle='#354b3b';ctx.fillRect(548,320,104,160);ctx.fillStyle='#788f77';ctx.fillRect(525,270,40,64);ctx.fillRect(635,270,40,64);ctx.fillStyle='#815b45';ctx.beginPath();ctx.moveTo(500,292);ctx.lineTo(600,220);ctx.lineTo(700,292);ctx.fill();ctx.fillStyle='#51d6d6';ctx.fillRect(576,376,48,104);bar(480,198,240,15,tower.hp/tower.maxHp,'#261616','#62d68a');ctx.fillStyle='#efe5bc';ctx.font='bold 16px monospace';ctx.textAlign='center';ctx.fillText('중앙 수호탑',600,186);ctx.textAlign='left'}
function drawHero(){ctx.save();ctx.translate(hero.x,hero.y);ctx.fillStyle='#0e1511';ctx.fillRect(-18,24,36,7);ctx.fillStyle='#e0bc98';ctx.fillRect(-11,-27,22,21);ctx.fillStyle=H[type][7];ctx.fillRect(-15,-6,30,29);ctx.fillStyle='#222c27';ctx.fillRect(-11,16,9,13);ctx.fillRect(2,16,9,13);ctx.fillStyle='#ded2bb';if(type==='warrior')ctx.fillRect(17,-10,6,38);else if(type==='mage'){ctx.fillRect(18,-30,5,51);ctx.fillStyle='#73dcef';ctx.fillRect(13,-34,15,6)}else{ctx.strokeStyle='#b8783e';ctx.lineWidth=4;ctx.beginPath();ctx.arc(19,0,17,-1.7,1.7);ctx.stroke()}ctx.restore()}
function drawEnemy(e){let d=T[e.k],col=e.k==='boss'?'#b83f4c':e.k==='tank'?'#708466':e.k==='caster'?'#8064ac':e.k==='runner'?'#b6a957':'#9a7459';ctx.fillStyle=col;ctx.fillRect(e.x-d[5],e.y-d[5],d[5]*2,d[5]*2);ctx.fillStyle='#231712';ctx.fillRect(e.x-d[5]*.5,e.y-d[5]*.2,5,5);ctx.fillRect(e.x+d[5]*.2,e.y-d[5]*.2,5,5);bar(e.x-d[5],e.y-d[5]-9,d[5]*2,5,e.hp/e.max,'#281717','#d95f63')}
function drawShot(s){ctx.fillStyle=type==='mage'?'#72dbed':'#ead27a';ctx.fillRect(s.x|0,s.y|0,type==='mage'?8:6,4)}
function drawHud(){ctx.fillStyle='#09110d';ctx.fillRect(14,14,375,112);ctx.fillStyle='#efd174';ctx.font='bold 20px monospace';ctx.fillText('WAVE '+wave,28,40);ctx.fillStyle='#d4e1da';ctx.font='13px monospace';ctx.fillText(gates[side][0]+' 방향 · '+spawned+'/'+count(),28,63);ctx.fillText('LV '+level+' · XP '+xp+'/'+nextXp,28,84);ctx.fillText('GOLD '+gold+' · [I] 상점 · [Q] 스킬',28,105);ctx.fillStyle='#09110d';ctx.fillRect(895,14,291,112);ctx.fillStyle='#d8ece1';ctx.fillText('수호탑 HP',913,38);bar(913,47,253,14,tower.hp/tower.maxHp,'#281717','#63d78a');ctx.fillText('영웅 HP '+Math.ceil(hero.hp)+'/'+hero.maxHp,913,78);bar(913,87,253,12,hero.hp/hero.maxHp,'#281717','#4b9ee1');ctx.fillText('Q '+(hero.skill>0?hero.skill.toFixed(1)+'s':'READY')+' · '+H[type][0],913,114)}
function bar(x,y,w,h,p,bg,fg){ctx.fillStyle=bg;ctx.fillRect(x,y,w,h);ctx.fillStyle=fg;ctx.fillRect(x+2,y+2,(w-4)*Math.max(0,Math.min(1,p)),h-4)}
document.getElementById('startBtn').onclick=()=>{hide('start');show('heroSelect')};document.getElementById('warriorBtn').onclick=()=>start('warrior');document.getElementById('mageBtn').onclick=()=>start('mage');document.getElementById('rangerBtn').onclick=()=>start('ranger');document.getElementById('restartBtn').onclick=menu;document.getElementById('resumeBtn').onclick=()=>{state='play';hide('pause')};document.getElementById('shopClose').onclick=shop;hide('heroSelect');hide('levelUp');hide('shop');hide('pause');hide('gameover');show('start');requestAnimationFrame(function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)});
})();