const field=document.getElementById('field'),enemyLayer=document.getElementById('enemyLayer'),pickupLayer=document.getElementById('pickupLayer'),stackLayer=document.getElementById('stackLayer'),player=document.getElementById('player'),base=document.getElementById('base'),resourceEl=document.getElementById('resource'),waveEl=document.getElementById('wave'),hpEl=document.getElementById('hp'),addBtn=document.getElementById('addUnit'),message=document.getElementById('message');
let resource=0,wave=1,hp=100,units=1,enemies=[],items=[],last=performance.now(),spawn=0,attack=0,gameOver=false;
const playerPos=()=>({x:innerWidth/2,y:innerHeight*.62});
function setResource(v){resource=v;resourceEl.textContent=v;addBtn.disabled=v<100||gameOver}
function flash(t){message.textContent=t;message.classList.remove('show');void message.offsetWidth;message.classList.add('show')}
function makeStackItem(){const el=document.createElement('div');el.className='stack-item';stackLayer.appendChild(el);return el}
function renderStack(){const p=playerPos();Array.from(stackLayer.children).forEach((el,i)=>{const col=i%2,row=Math.floor(i/2);el.style.left=(p.x+(col?10:-10)-7)+'px';el.style.top=(p.y-25-row*15)+'px';el.style.zIndex=30+i})}
function spawnEnemy(){const side=Math.floor(Math.random()*3);const x=side===0?-40:side===1?innerWidth+40:Math.random()*innerWidth;const y=side===2?-45:80+Math.random()*innerHeight*.2;const el=document.createElement('div');el.className='enemy';el.innerHTML='<div class="hpbar"><i></i></div>';enemyLayer.appendChild(el);enemies.push({el,x,y,hp:25+wave*7,max:25+wave*7,speed:28+wave*2,dead:false})}
function drop(e){const n=1+Math.floor(Math.random()*2);for(let i=0;i<n;i++){const el=document.createElement('div');el.className='pickup';pickupLayer.appendChild(el);items.push({el,x:e.x+(Math.random()-.5)*35,y:e.y+(Math.random()-.5)*25,value:10})}}
function attackNearest(){if(gameOver)return;const p=playerPos();let live=enemies.filter(e=>!e.dead);if(!live.length)return;let e=live.sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];const d=Math.hypot(e.x-p.x,e.y-p.y);if(d<125){e.hp-=12+units*3;player.classList.add('attack');setTimeout(()=>player.classList.remove('attack'),120);const hit=document.createElement('div');hit.className='slash';hit.style.left=e.x+'px';hit.style.top=e.y+'px';field.appendChild(hit);setTimeout(()=>hit.remove(),180);if(e.hp<=0){e.dead=true;drop(e);e.el.remove();flash('ITEM +');checkWave()}}}
function checkWave(){if(enemies.length&&enemies.every(e=>e.dead)){wave++;waveEl.textContent=wave;flash('WAVE '+wave)}}
function update(dt){if(gameOver)return;const p=playerPos();spawn+=dt;attack+=dt;if(spawn>Math.max(380,1150-wave*55)){spawn=0;spawnEnemy()}if(attack>430){attack=0;attackNearest()}
 for(const e of enemies){if(e.dead)continue;const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy);if(d>48){e.x+=dx/d*e.speed*dt/1000;e.y+=dy/d*e.speed*dt/1000}else if(Math.random()<dt/900){hp=Math.max(0,hp-5);hpEl.textContent=hp;if(hp<=0){gameOver=true;flash('GAME OVER')}}e.el.style.left=e.x-17+'px';e.el.style.top=e.y-22+'px';e.el.querySelector('i').style.width=Math.max(0,e.hp/e.max*100)+'%'}
 for(let i=items.length-1;i>=0;i--){const it=items[i],dx=p.x-it.x,dy=p.y-it.y,d=Math.hypot(dx,dy);if(d<110){it.x+=dx*.1;it.y+=dy*.1}it.el.style.left=it.x-7+'px';it.el.style.top=it.y-7+'px';if(d<22){it.el.remove();items.splice(i,1);resource+=it.value;setResource(resource);const s=makeStackItem();s.dataset.n=stackLayer.children.length;renderStack()}}
 renderStack()}
addBtn.onclick=()=>{if(resource>=100&&!gameOver){resource-=100;units++;setResource(resource);flash('동료 +1')}};
field.addEventListener('pointerdown',e=>{const p=playerPos();const dx=e.clientX-p.x,dy=e.clientY-p.y;player.style.transform=`translateX(-50%) rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`;setTimeout(()=>player.style.transform='translateX(-50%)',250)});
function loop(now){const dt=Math.min(50,now-last);last=now;update(dt);requestAnimationFrame(loop)}
setResource(0);for(let i=0;i<4;i++)setTimeout(spawnEnemy,i*450);requestAnimationFrame(loop);window.addEventListener('resize',renderStack);