(()=>{'use strict';
const host=document.getElementById('canvas'),c=document.createElement('canvas'),ctx=c.getContext('2d');c.id='gameCanvas';host.replaceChildren(c);ctx.imageSmoothingEnabled=false;
const W=960,H=720,TAU=Math.PI*2;let scale=1,last=0,t=0,running=false,paused=false,over=false;
const hero={x:480,y:500,hp:260,maxHp:260,spd:210,damage:34,rate:.45,cool:0,dir:'up'};
const tower={x:480,y:360,hp:1000,maxHp:1000};
let wave=1,side=0,sideActive=false,spawnTimer=0,kills=0,gold=120,level=1,xp=0,nextXp=80,enemies=[],particles=[],texts=[],keys={};
const DIRS=[{name:'북',x:480,y:42,dx:0,dy:1},{name:'동',x:918,y:360,dx:-1,dy:0},{name:'남',x:480,y:678,dx:0,dy:-1},{name:'서',x:42,y:360,dx:1,dy:0}];
const TYPES={grunt:{hp:48,spd:46,dmg:8,gold:5,xp:10,kind:'mole',size:2},runner:{hp:30,spd:82,dmg:6,gold:7,xp:13,kind:'mole',size:1.8},tank:{hp:180,spd:27,dmg:18,gold:16,xp:27,kind:'treant',size:2.6},elite:{hp:340,spd:35,dmg:25,gold:32,xp:55,kind:'treant',size:3},boss:{hp:1800,spd:20,dmg:45,gold:180,xp:300,kind:'treant',size:4}};
const img=(src)=>{const i=new Image();i.src=src;return i};
const heroSheets={front:img('https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/spritesheets/hero/walk/hero-walk-front.png'),back:img('https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/spritesheets/hero/walk/hero-walk-back.png'),side:img('https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/spritesheets/hero/walk/hero-walk-side.png')};
const enemySheets={mole:{front:img('https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/spritesheets/mole/walk/mole-walk-front.png'),back:img('https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/spritesheets/mole/walk/mole-walk-back.png'),side:img('https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/spritesheets/mole/walk/mole-walk-side.png')},treant:{front:img('https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/spritesheets/treant/walk/treant-walk-front.png'),back:img('https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/spritesheets/treant/walk/treant-walk-back.png'),side:img('https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/spritesheets/treant/walk/treant-walk-side.png')}};
const tileSheet=img('https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/tiles.png');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rnd=(a,b)=>a+Math.random()*(b-a);
function resize(){let r=host.getBoundingClientRect();scale=Math.min(r.width/W,r.height/H);c.width=W;c.height=H;c.style.width=W*scale+'px';c.style.height=H*scale+'px'}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{let k=e.key.toLowerCase();keys[k]=1;if(k==='q')skill();if(k==='escape'&&running&&!over){paused=!paused;document.getElementById('pause').classList.toggle('hidden',!paused)}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
function txt(x,y,s,n=14,col='#fff'){ctx.font=`bold ${n}px monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#071014';ctx.fillText(s,x+2,y+2);ctx.fillStyle=col;ctx.fillText(s,x,y)}function rect(x,y,w,h,col){ctx.fillStyle=col;ctx.fillRect(x|0,y|0,w|0,h|0)}function bar(x,y,w,h,p,bg,fg){rect(x,y,w,h,bg);rect(x+2,y+2,(w-4)*clamp(p,0,1),h-4,fg)}
function particle(x,y,col,n=8){for(let i=0;i<n;i++){let a=rnd(0,TAU),s=rnd(25,100);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.5,max:.5,col})}}function dtext(x,y,s,col='#ffd66b'){texts.push({x,y,s,life:.7,col})}
function gainXP(v){xp+=v;if(xp>=nextXp){xp-=nextXp;level++;nextXp=Math.floor(nextXp*1.24);upgrade()}}
const upgrades=[['공격력','기본 공격력 +18',()=>hero.damage+=18],['공격속도','공격 속도 증가',()=>hero.rate=Math.max(.18,hero.rate*.8)],['강화갑옷','최대 HP +90',()=>{hero.maxHp+=90;hero.hp=hero.maxHp}],['질주','이동 속도 +40',()=>hero.spd+=40],['전격','전격 피해 +45%',()=>skillPower*=1.45]];let skillPower=120;
function upgrade(){paused=true;let box=document.getElementById('upgradeChoices');if(!box)return;document.getElementById('upgrade').classList.remove('hidden');box.innerHTML='';[...upgrades].sort(()=>Math.random()-.5).slice(0,3).forEach(u=>{let b=document.createElement('button');b.className='upgradeChoice';b.innerHTML=`<strong>${u[0]}</strong><small>${u[1]}</small>`;b.onclick=()=>{u[2]();paused=false;document.getElementById('upgrade').classList.add('hidden')};box.appendChild(b)})}
function beginSide(){sideActive=true;sideRemaining=5+wave*2;spawnTimer=0;let d=DIRS[side];document.getElementById('toast').textContent=`${d.name}쪽 적군 접근`;document.getElementById('toast').classList.add('show')}
let sideRemaining=0;
function spawn(){if(!sideActive||sideRemaining<=0)return;let d=DIRS[side],r=Math.random(),type=r<.15?'runner':r<.27?'tank':r<.33?'elite':'grunt';if(wave%10===0&&side===3&&sideRemaining===1)type='boss';let z=TYPES[type],hp=z.hp*(1+wave*.07);enemies.push({type,x:d.x+rnd(-20,20),y:d.y+rnd(-20,20),hp,max:hp,spd:z.spd*(1+Math.min(.5,wave*.012)),dmg:z.dmg*(1+wave*.05),phase:rnd(0,TAU),hit:0});sideRemaining--;spawnTimer=.7}
function kill(e){let z=TYPES[e.type];e.dead=1;kills++;gold+=z.gold;gainXP(z.xp);particle(e.x,e.y,e.type==='boss'?'#ff7070':'#f5ca55',12);dtext(e.x,e.y-22,'+'+z.gold+'G');if(e.type==='boss')document.getElementById('toast').textContent='보스 처치!'}
function attack(){if(hero.cool>0)return;let target,en=999;for(let e of enemies){if(e.dead)continue;let d=dist(hero,e);if(d<145&&d<en){en=d;target=e}}if(!target)return;hero.cool=hero.rate;hero.dir=Math.abs(target.x-hero.x)>Math.abs(target.y-hero.y)?(target.x<hero.x?'left':'right'):(target.y<hero.y?'up':'down');let v=hero.damage;target.hp-=v;target.hit=.1;dtext(target.x,target.y-20,Math.round(v),'#fff');particle(target.x,target.y,'#d8e7ef',4);if(target.hp<=0)kill(target)}
function skill(){if(!running||paused||over||skillCd>0)return;skillCd=7;for(let e of enemies){if(!e.dead&&dist(hero,e)<170){e.hp-=skillPower;if(e.hp<=0)kill(e)}}particle(hero.x,hero.y,'#62e4f5',30)}let skillCd=0;
function move(dt){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(dx||dy){let n=Math.hypot(dx,dy);hero.x=clamp(hero.x+dx/n*hero.spd*dt,32,928);hero.y=clamp(hero.y+dy/n*hero.spd*dt,32,688);hero.dir=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down')}}
function update(dt){if(!running||paused||over)return;skillCd=Math.max(0,skillCd-dt);hero.cool=Math.max(0,hero.cool-dt);move(dt);attack();spawnTimer-=dt;if(!sideActive)beginSide();else if(spawnTimer<=0&&sideRemaining>0)spawn();for(let e of enemies){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);let dx=tower.x-e.x,dy=tower.y-e.y,d=Math.hypot(dx,dy);if(d<48)tower.hp-=e.dmg*dt;else{e.x+=dx/d*e.spd*dt;e.y+=dy/d*e.spd*dt}}enemies=enemies.filter(e=>!e.dead);if(sideActive&&sideRemaining===0&&enemies.length===0){sideActive=false;side=(side+1)%4;if(side===0){wave++;tower.hp=Math.min(tower.maxHp,tower.hp+55)}}for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt}particles=particles.filter(p=>p.life>0);for(let a of texts){a.y-=20*dt;a.life-=dt}texts=texts.filter(a=>a.life>0);if(tower.hp<=0)gameOver()}
function drawMap(){ctx.fillStyle='#182820';ctx.fillRect(0,0,W,H);if(tileSheet.complete&&tileSheet.naturalWidth){const tw=16,th=16,cols=Math.floor(tileSheet.naturalWidth/tw);for(let y=0;y<H;y+=16)for(let x=0;x<W;x+=16){let idx=((x/16|0)+(y/16|0)*3)%Math.min(cols*3,96);let sx=(idx%cols)*tw,sy=Math.floor(idx/cols)*th;ctx.drawImage(tileSheet,sx,sy,tw,th,x,y,16,16)}}else{for(let y=0;y<H;y+=32)for(let x=0;x<W;x+=32)rect(x,y,32,32,'#1b2a22')}ctx.strokeStyle='#3b493f';ctx.lineWidth=38;for(let d of DIRS){ctx.beginPath();ctx.moveTo(d.x,d.y);ctx.lineTo(480,360);ctx.stroke()}}
function drawSheet(imgObj,x,y,size,frame,flip=false){if(!imgObj.complete||!imgObj.naturalWidth)return false;const frames=4,sw=imgObj.naturalWidth/frames,sh=imgObj.naturalHeight;ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(imgObj,(frame%frames)*sw,0,sw,sh,-sw*size/2,-sh*size/2,sw*size,sh*size);ctx.restore();return true}
function drawEnemy(e){let z=TYPES[e.type],dX=tower.x-e.x,dY=tower.y-e.y,vertical=Math.abs(dY)>Math.abs(dX),sheet=vertical?(dY<0?enemySheets[z.kind].back:enemySheets[z.kind].front):enemySheets[z.kind].side,flip=!vertical&&dX<0;drawSheet(sheet,e.x,e.y,z.size,Math.floor(t*8)%4,flip)}
function heroSprite(){let vertical=hero.dir==='up'||hero.dir==='down',sheet=vertical?(hero.dir==='up'?heroSheets.back:heroSheets.front):heroSheets.side,flip=hero.dir==='left';drawSheet(sheet,hero.x,hero.y,2.2,Math.floor(t*8)%4,flip)}
function castle(){ctx.fillStyle='#33484c';ctx.beginPath();ctx.arc(480,360,118,0,TAU);ctx.fill();ctx.strokeStyle='#697b7d';ctx.lineWidth=12;ctx.stroke();rect(420,295,120,130,'#526469');rect(438,313,84,112,'#28393e');for(let x=425;x<535;x+=18)rect(x,276,11,20,'#7a8989');rect(466,340,28,85,'#58dce5');txt(480,250,'중앙 수호탑',16,'#edf5ef');bar(390,226,180,12,tower.hp/tower.maxHp,'#151b1d','#63d18a')}
function draw(){drawMap();castle();for(let e of enemies){drawEnemy(e);let z=TYPES[e.type];bar(e.x-16*z.size,e.y-16*z.size-9,32*z.size,5,e.hp/e.max,'#2a171b','#e36a67')}heroSprite();for(let p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);rect(p.x,p.y,4,4,p.col);ctx.globalAlpha=1}for(let a of texts){ctx.globalAlpha=clamp(a.life/.7,0,1);txt(a.x,a.y,a.s,12,a.col);ctx.globalAlpha=1}rect(12,12,280,82,'#0b1417');txt(28,32,`WAVE ${wave}`,18,'#f4d06f');txt(28,57,`${DIRS[side].name} 방향`,12,'#80d8e3');txt(28,77,`LV ${level}  XP ${xp}/${nextXp}`,11,'#b8ccc8');rect(668,12,280,82,'#0b1417');txt(684,32,`탑 HP ${Math.ceil(tower.hp)}/${tower.maxHp}`,12,'#e0ece8');bar(684,45,230,9,tower.hp/tower.maxHp,'#292426','#63d18a');txt(684,76,`G ${gold}   처치 ${kills}`,12,'#ffd66b');txt(480,115,skillCd>0?`Q 전격 ${skillCd.toFixed(1)}초`:'Q 전격 준비 완료',12,'#70dff4')}
function gameOver(){over=true;running=false;document.getElementById('gameover').classList.remove('hidden');document.getElementById('gameoverDetail').textContent=`웨이브 ${wave} · 레벨 ${level} · 처치 ${kills}`}function reset(){Object.assign(hero,{x:480,y:500,hp:260,maxHp:260,spd:210,damage:34,rate:.45,cool:0,dir:'up'});tower.hp=1000;wave=1;side=0;sideActive=false;sideRemaining=0;spawnTimer=0;kills=0;gold=120;level=1;xp=0;nextXp=80;skillCd=0;enemies=[];particles=[];texts=[];running=true;paused=false;over=false;document.querySelectorAll('.overlay').forEach(e=>e.classList.add('hidden'));document.getElementById('toast').textContent='북 → 동 → 남 → 서 순서로 공격합니다'}document.getElementById('startBtn').onclick=reset;document.getElementById('restartBtn').onclick=reset;document.getElementById('resumeBtn').onclick=()=>{paused=false;document.getElementById('pause').classList.add('hidden')};function loop(now){let dt=Math.min(.033,(now-last)/1000||0);last=now;t+=dt;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop)})();