(()=>{'use strict';
const host=document.getElementById('canvas'),c=document.createElement('canvas'),ctx=c.getContext('2d');c.id='gameCanvas';host.replaceChildren(c);ctx.imageSmoothingEnabled=false;
const W=960,H=720,TAU=Math.PI*2,TILE=16,MAP_SCALE=2;let scale=1,last=0,t=0,running=false,paused=false,over=false,heroMoving=false;
const hero={x:480,y:500,hp:260,maxHp:260,spd:210,damage:34,rate:.45,cool:0,dir:'up'};
const tower={x:480,y:360,hp:1000,maxHp:1000};
let wave=1,side=0,sideActive=false,spawnTimer=0,kills=0,gold=120,level=1,xp=0,nextXp=80,enemies=[],particles=[],texts=[],keys={};
const DIRS=[{name:'북',x:480,y:42,dx:0,dy:1},{name:'동',x:918,y:360,dx:-1,dy:0},{name:'남',x:480,y:678,dx:0,dy:-1},{name:'서',x:42,y:360,dx:1,dy:0}];
const TYPES={grunt:{hp:48,spd:46,dmg:8,gold:5,xp:10,kind:'mole',scale:2.1,frameW:24,frameH:24,frames:4},runner:{hp:30,spd:82,dmg:6,gold:7,xp:13,kind:'mole',scale:1.8,frameW:24,frameH:24,frames:4},tank:{hp:180,spd:27,dmg:18,gold:16,xp:27,kind:'treant',scale:2.2,frameW:31,frameH:35,frames:4},elite:{hp:340,spd:35,dmg:25,gold:32,xp:55,kind:'treant',scale:2.5,frameW:31,frameH:35,frames:4},boss:{hp:1800,spd:20,dmg:45,gold:180,xp:300,kind:'treant',scale:3.2,frameW:31,frameH:35,frames:4}};
const img=(src)=>{const i=new Image();i.crossOrigin='anonymous';i.src=src;return i};
const BASE='https://raw.githubusercontent.com/pierpo/phaser3-simple-rpg/master/assets/';
const heroSheets={front:img(BASE+'spritesheets/hero/walk/hero-walk-front.png'),back:img(BASE+'spritesheets/hero/walk/hero-walk-back.png'),side:img(BASE+'spritesheets/hero/walk/hero-walk-side.png')};
const enemySheets={mole:{front:img(BASE+'spritesheets/mole/walk/mole-walk-front.png'),back:img(BASE+'spritesheets/mole/walk/mole-walk-back.png'),side:img(BASE+'spritesheets/mole/walk/mole-walk-side.png')},treant:{front:img(BASE+'spritesheets/treant/walk/treant-walk-front.png'),back:img(BASE+'spritesheets/treant/walk/treant-walk-back.png'),side:img(BASE+'spritesheets/treant/walk/treant-walk-side.png')}};
const tileSheet=img(BASE+'environment/tileset.png');
const MAP_URL=BASE+'map.tmx';
let mapLayers=[],mapLoaded=false;
fetch(MAP_URL).then(r=>{if(!r.ok)throw new Error('map load failed');return r.text()}).then(text=>{const xml=new DOMParser().parseFromString(text,'application/xml');const layers=[...xml.querySelectorAll('layer')];mapLayers=layers.map(layer=>{const data=layer.querySelector('data');if(!data)return null;const encoding=data.getAttribute('encoding');let values=[];if(encoding==='csv'){values=data.textContent.trim().split(',').map(v=>Number(v.trim())||0)}else if(encoding==='base64'){const raw=atob(data.textContent.trim()),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);for(let i=0;i+3<bytes.length;i+=4)values.push((bytes[i])|(bytes[i+1]<<8)|(bytes[i+2]<<16)|(bytes[i+3]<<24))}return {width:Number(layer.getAttribute('width'))||40,height:Number(layer.getAttribute('height'))||40,values}}).filter(Boolean);mapLoaded=mapLayers.length>0}).catch(()=>{mapLayers=[];mapLoaded=false});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rnd=(a,b)=>a+Math.random()*(b-a);
function resize(){let r=host.getBoundingClientRect();scale=Math.min(r.width/W,r.height/H);c.width=W;c.height=H;c.style.width=Math.floor(W*scale)+'px';c.style.height=Math.floor(H*scale)+'px'}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{let k=e.key.toLowerCase();keys[k]=1;if(k==='q')skill();if(k==='escape'&&running&&!over){paused=!paused;document.getElementById('pause').classList.toggle('hidden',!paused)}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
function txt(x,y,s,n=14,col='#fff'){ctx.font=`bold ${n}px monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#071014';ctx.fillText(s,x+2,y+2);ctx.fillStyle=col;ctx.fillText(s,x,y)}function rect(x,y,w,h,col){ctx.fillStyle=col;ctx.fillRect(x|0,y|0,w|0,h|0)}function bar(x,y,w,h,p,bg,fg){rect(x,y,w,h,bg);rect(x+2,y+2,(w-4)*clamp(p,0,1),h-4,fg)}
function particle(x,y,col,n=8){for(let i=0;i<n;i++){let a=rnd(0,TAU),s=rnd(25,100);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.5,max:.5,col})}}function dtext(x,y,s,col='#ffd66b'){texts.push({x,y,s,life:.7,col})}
function gainXP(v){xp+=v;if(xp>=nextXp){xp-=nextXp;level++;nextXp=Math.floor(nextXp*1.24);upgrade()}}
const upgrades=[['공격력','기본 공격력 +18',()=>hero.damage+=18],['공격속도','공격 속도 증가',()=>hero.rate=Math.max(.18,hero.rate*.8)],['강화갑옷','최대 HP +90',()=>{hero.maxHp+=90;hero.hp=hero.maxHp}],['질주','이동 속도 +40',()=>hero.spd+=40],['전격','전격 피해 +45%',()=>skillPower*=1.45]];let skillPower=120;
function upgrade(){paused=true;let box=document.getElementById('upgradeChoices');if(!box)return;document.getElementById('upgrade').classList.remove('hidden');box.innerHTML='';[...upgrades].sort(()=>Math.random()-.5).slice(0,3).forEach(u=>{let b=document.createElement('button');b.className='upgradeChoice';b.innerHTML=`<strong>${u[0]}</strong><small>${u[1]}</small>`;b.onclick=()=>{u[2]();paused=false;document.getElementById('upgrade').classList.add('hidden')};box.appendChild(b)})}
let sideRemaining=0;
function beginSide(){sideActive=true;sideRemaining=5+wave*2;spawnTimer=0;let d=DIRS[side];document.getElementById('toast').textContent=`${d.name}쪽 적군 접근`;document.getElementById('toast').classList.add('show')}
function spawn(){if(!sideActive||sideRemaining<=0)return;let d=DIRS[side],r=Math.random(),type=r<.15?'runner':r<.27?'tank':r<.33?'elite':'grunt';if(wave%10===0&&side===3&&sideRemaining===1)type='boss';let z=TYPES[type],hp=z.hp*(1+wave*.07);enemies.push({type,x:d.x+rnd(-20,20),y:d.y+rnd(-20,20),hp,max:hp,spd:z.spd*(1+Math.min(.5,wave*.012)),dmg:z.dmg*(1+wave*.05),phase:rnd(0,TAU),hit:0});sideRemaining--;spawnTimer=.7}
function kill(e){let z=TYPES[e.type];e.dead=1;kills++;gold+=z.gold;gainXP(z.xp);particle(e.x,e.y,e.type==='boss'?'#ff7070':'#f5ca55',12);dtext(e.x,e.y-22,'+'+z.gold+'G');if(e.type==='boss')document.getElementById('toast').textContent='보스 처치!'}
function attack(){if(hero.cool>0)return;let target,en=999;for(let e of enemies){if(e.dead)continue;let d=dist(hero,e);if(d<145&&d<en){en=d;target=e}}if(!target)return;hero.cool=hero.rate;hero.dir=Math.abs(target.x-hero.x)>Math.abs(target.y-hero.y)?(target.x<hero.x?'left':'right'):(target.y<hero.y?'up':'down');let v=hero.damage;target.hp-=v;target.hit=.1;dtext(target.x,target.y-20,Math.round(v),'#fff');particle(target.x,target.y,'#d8e7ef',4);if(target.hp<=0)kill(target)}
function skill(){if(!running||paused||over||skillCd>0)return;skillCd=7;for(let e of enemies){if(!e.dead&&dist(hero,e)<170){e.hp-=skillPower;if(e.hp<=0)kill(e)}}particle(hero.x,hero.y,'#62e4f5',30)}let skillCd=0;
function move(dt){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);heroMoving=!!(dx||dy);if(dx||dy){let n=Math.hypot(dx,dy);hero.x=clamp(hero.x+dx/n*hero.spd*dt,32,928);hero.y=clamp(hero.y+dy/n*hero.spd*dt,32,688);hero.dir=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down')}}
function update(dt){if(!running||paused||over)return;skillCd=Math.max(0,skillCd-dt);hero.cool=Math.max(0,hero.cool-dt);move(dt);attack();spawnTimer-=dt;if(!sideActive)beginSide();else if(spawnTimer<=0&&sideRemaining>0)spawn();for(let e of enemies){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);let dx=tower.x-e.x,dy=tower.y-e.y,d=Math.hypot(dx,dy);if(d<48)tower.hp-=e.dmg*dt;else{e.x+=dx/d*e.spd*dt;e.y+=dy/d*e.spd*dt}}enemies=enemies.filter(e=>!e.dead);if(sideActive&&sideRemaining===0&&enemies.length===0){sideActive=false;side=(side+1)%4;if(side===0){wave++;tower.hp=Math.min(tower.maxHp,tower.hp+55)}}for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt}particles=particles.filter(p=>p.life>0);for(let a of texts){a.y-=20*dt;a.life-=dt}texts=texts.filter(a=>a.life>0);if(tower.hp<=0)gameOver()}
function tile(id,x,y){if(!tileSheet.complete||!tileSheet.naturalWidth||id<=0)return;const gid=(id&0x1fffffff)-1;if(gid<0)return;const cols=34,sx=(gid%cols)*16,sy=Math.floor(gid/cols)*16;ctx.drawImage(tileSheet,sx,sy,16,16,x,y,32,32)}
function drawMap(){ctx.fillStyle='#101a17';ctx.fillRect(0,0,W,H);if(mapLoaded&&tileSheet.complete&&tileSheet.naturalWidth){const ox=-160,oy=-280;for(const layer of mapLayers){for(let row=0;row<layer.height;row++){for(let col=0;col<layer.width;col++){const gid=layer.values[row*layer.width+col]||0;if(gid)tile(gid,col*32+ox,row*32+oy)}}}}else if(tileSheet.complete&&tileSheet.naturalWidth){const safeGrass=625;for(let y=-280;y<440;y+=32)for(let x=-160;x<800;x+=32)tile(safeGrass,x,y)}}
function drawSheet(imgObj,x,y,scalePx,frame,frameW,frameH,frameCount,flip=false){if(!imgObj.complete||!imgObj.naturalWidth)return false;const f=Math.max(0,Math.min(frameCount-1,frame));ctx.save();ctx.translate(Math.round(x),Math.round(y));if(flip)ctx.scale(-1,1);ctx.drawImage(imgObj,f*frameW,0,frameW,frameH,Math.round(-frameW*scalePx/2),Math.round(-frameH*scalePx/2),Math.round(frameW*scalePx),Math.round(frameH*scalePx));ctx.restore();return true}
function drawEnemy(e){let z=TYPES[e.type],dx=tower.x-e.x,dy=tower.y-e.y,vertical=Math.abs(dy)>Math.abs(dx),sheet=vertical?(dy<0?enemySheets[z.kind].back:enemySheets[z.kind].front):enemySheets[z.kind].side,flip=!vertical&&dx<0;drawSheet(sheet,e.x,e.y,z.scale,Math.floor(t*7)%z.frames,z.frameW,z.frameH,z.frames,flip)}
function heroSprite(){let vertical=hero.dir==='up'||hero.dir==='down',sheet=vertical?(hero.dir==='up'?heroSheets.back:heroSheets.front):heroSheets.side;const frame=heroMoving?Math.floor(t*9)%3:1;drawSheet(sheet,hero.x,hero.y,2,frame,32,32,3,hero.dir==='left')}
function castle(){ctx.fillStyle='#33484c';ctx.beginPath();ctx.arc(480,360,118,0,TAU);ctx.fill();ctx.strokeStyle='#697b7d';ctx.lineWidth=12;ctx.stroke();rect(420,295,120,130,'#526469');rect(438,313,84,112,'#28393e');for(let x=425;x<535;x+=18)rect(x,276,11,20,'#7a8989');rect(466,340,28,85,'#58dce5');txt(480,250,'중앙 수호탑',16,'#edf5ef');bar(390,226,180,12,tower.hp/tower.maxHp,'#151b1d','#63d18a')}
function draw(){drawMap();castle();for(let e of enemies){drawEnemy(e);let z=TYPES[e.type];bar(e.x-16*z.scale,e.y-16*z.scale-9,32*z.scale,5,e.hp/e.max,'#2a171b','#e36a67')}heroSprite();for(let p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);rect(p.x,p.y,4,4,p.col);ctx.globalAlpha=1}for(let a of texts){ctx.globalAlpha=clamp(a.life/.7,0,1);txt(a.x,a.y,a.s,12,a.col);ctx.globalAlpha=1}rect(12,12,280,82,'#0b1417');txt(28,32,`WAVE ${wave}`,18,'#f4d06f');txt(28,57,`${DIRS[side].name} 방향`,12,'#80d8e3');txt(28,77,`LV ${level}  XP ${xp}/${nextXp}`,11,'#b8ccc8');rect(668,12,280,82,'#0b1417');txt(684,32,`탑 HP ${Math.ceil(tower.hp)}/${tower.maxHp}`,12,'#e0ece8');bar(684,45,230,9,tower.hp/tower.maxHp,'#292426','#63d18a');txt(684,76,`G ${gold}   처치 ${kills}`,12,'#ffd66b');txt(480,115,skillCd>0?`Q 전격 ${skillCd.toFixed(1)}초`:'Q 전격 준비 완료',12,'#70dff4')}
function gameOver(){over=true;running=false;document.getElementById('gameover').classList.remove('hidden');document.getElementById('gameoverDetail').textContent=`웨이브 ${wave} · 레벨 ${level} · 처치 ${kills}`}function reset(){Object.assign(hero,{x:480,y:500,hp:260,maxHp:260,spd:210,damage:34,rate:.45,cool:0,dir:'up'});tower.hp=1000;wave=1;side=0;sideActive=false;sideRemaining=0;spawnTimer=0;kills=0;gold=120;level=1;xp=0;nextXp=80;skillCd=0;enemies=[];particles=[];texts=[];heroMoving=false;running=true;paused=false;over=false;document.querySelectorAll('.overlay').forEach(e=>e.classList.add('hidden'));document.getElementById('toast').textContent='북 → 동 → 남 → 서 순서로 공격합니다'}document.getElementById('startBtn').onclick=reset;document.getElementById('restartBtn').onclick=reset;document.getElementById('resumeBtn').onclick=()=>{paused=false;document.getElementById('pause').classList.add('hidden')};function loop(now){let dt=Math.min(.033,(now-last)/1000||0);last=now;t+=dt;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop)})();