import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';

const $=id=>document.getElementById(id), root=$('canvas');
const show=id=>$(id)?.classList.remove('hidden'), hide=id=>$(id)?.classList.add('hidden');
const hideAll=()=>['start','heroSelect','levelUp','shop','equipment','pause','gameover'].forEach(hide);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.domElement.id='gameCanvas';root.replaceChildren(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x111914);scene.fog=new THREE.Fog(0x111914,30,60);
const camera=new THREE.OrthographicCamera(-14,14,10,-10,.1,100);camera.position.set(15,19,15);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0xd4e8da,0x172019,2));const sun=new THREE.DirectionalLight(0xffe7ba,2.2);sun.position.set(9,22,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const material=(c,e=0)=>new THREE.MeshStandardMaterial({color:c,roughness:.88,emissive:e,emissiveIntensity:e?1.25:0});
const box=(x,y,z,sx,sy,sz,c)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),material(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m};
const cyl=(x,y,z,r,h,c)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,10),material(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m};
const ground=new THREE.Mesh(new THREE.PlaneGeometry(38,38),material(0x2a4030));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const arena=new THREE.Mesh(new THREE.CircleGeometry(9.2,40),material(0x38523d));arena.rotation.x=-Math.PI/2;arena.position.y=.02;scene.add(arena);
box(0,.05,-8.6,4,.08,14,0x304938);box(8.6,.05,0,14,.08,4,0x304938);box(0,.05,8.6,4,.08,14,0x304938);box(-8.6,.05,0,14,.08,4,0x304938);
box(0,1.35,0,5.8,2.7,5,0x667b68);for(const [x,z] of [[-3.1,-2.4],[3.1,-2.4],[-3.1,2.4],[3.1,2.4]])cyl(x,2,z,.72,4.1,0x768b75);box(0,1.15,2.75,1.55,2.3,.7,0x412d25);const roof=new THREE.Mesh(new THREE.ConeGeometry(3.5,2,4),material(0x855845));roof.position.y=3.9;roof.rotation.y=Math.PI/4;scene.add(roof);const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(.58),material(0x55d8d0,0x154946));crystal.position.set(0,3,2.98);scene.add(crystal);
const gates=[new THREE.Vector3(0,0,-15),new THREE.Vector3(15,0,0),new THREE.Vector3(0,0,15),new THREE.Vector3(-15,0,0)],gateNames=['북','동','남','서'];
const models={warrior:'https://raw.githubusercontent.com/euuuuuuan/hollowmere-public/main/public/models/char/Knight.glb',mage:'https://raw.githubusercontent.com/euuuuuuan/hollowmere-public/main/public/models/char/Mage.glb',ranger:'https://cdn.3dassets.dev/assets/28865/v1/model.glb',grunt:'https://raw.githubusercontent.com/euuuuuuan/hollowmere-public/main/public/models/char/Skeleton_Minion.glb',runner:'https://raw.githubusercontent.com/euuuuuuan/hollowmere-public/main/public/models/char/Skeleton_Rogue.glb',caster:'https://raw.githubusercontent.com/euuuuuuan/hollowmere-public/main/public/models/char/Skeleton_Mage.glb',tank:'https://raw.githubusercontent.com/euuuuuuan/hollowmere-public/main/public/models/char/Skeleton_Shield_Large_A.gltf'};
const loader=new GLTFLoader(),cache=new Map();
function loadModel(k){if(cache.has(k))return cache.get(k);const p=loader.loadAsync(models[k]);cache.set(k,p);return p;}
function fit(src,h){const o=src.scene.clone(true);const b=new THREE.Box3().setFromObject(o),sc=h/Math.max(.01,b.max.y-b.min.y);o.scale.setScalar(sc);const b2=new THREE.Box3().setFromObject(o);o.position.y-=b2.min.y;o.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true}});return o}
function fallback(c,h){const g=new THREE.Group(),m=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.8,4,8),material(c));m.position.y=h*.5;g.add(m);return g}

const heroDefs={warrior:{name:'전사',hp:600,speed:6,damage:58,range:2.8,rate:.42,skill:7,color:0xc17d3f,model:'warrior'},mage:{name:'마법사',hp:380,speed:5.3,damage:72,range:5.6,rate:.48,skill:6,color:0x5d9bd7,model:'mage'},ranger:{name:'궁수',hp:430,speed:6.7,damage:52,range:6.6,rate:.38,skill:8,color:0x6eaa72,model:'ranger'}};
const enemyDefs={grunt:{hp:72,speed:1.55,dmg:8,gold:8,xp:10,h:1.25,c:0x98725c,model:'grunt'},runner:{hp:50,speed:2.95,dmg:6,gold:10,xp:14,h:1.15,c:0xb4a256,model:'runner'},tank:{hp:250,speed:.92,dmg:22,gold:28,xp:34,h:1.8,c:0x718469,model:'tank'},caster:{hp:125,speed:1.25,dmg:16,gold:26,xp:30,h:1.4,c:0x8062a5,model:'caster'},boss:{hp:3400,speed:.66,dmg:65,gold:520,xp:450,h:3.3,c:0xb9424b,model:'tank'}};
const slots={helmet:'투구',armor:'갑옷',gloves:'장갑',boots:'신발',weapon:'주무기',offhand:'보조무기',ring:'반지',amulet:'목걸이'};
const shopItems=[
 {id:'iron_sword',name:'강철검',slot:'weapon',cost:180,desc:'공격력 +35',stat:['damage',35],visual:'sword'},
 {id:'mage_staff',name:'마력 지팡이',slot:'weapon',cost:220,desc:'스킬 피해 +25%',stat:['power',.25],visual:'staff'},
 {id:'hunter_bow',name:'사냥꾼의 활',slot:'weapon',cost:220,desc:'공격력 +22 · 공격속도 +10%',stat:['damage',22],visual:'bow'},
 {id:'iron_helm',name:'철제 투구',slot:'helmet',cost:160,desc:'최대 HP +90',stat:['maxHp',90],visual:'helm'},
 {id:'plate',name:'수호 갑옷',slot:'armor',cost:260,desc:'최대 HP +180',stat:['maxHp',180],visual:'armor'},
 {id:'gloves',name:'전투 장갑',slot:'gloves',cost:150,desc:'공격력 +12',stat:['damage',12],visual:'gloves'},
 {id:'boots',name:'질주화',slot:'boots',cost:200,desc:'이동속도 +0.8',stat:['speed',.8],visual:'boots'},
 {id:'shield',name:'철제 방패',slot:'offhand',cost:220,desc:'수호탑 피해 경감',stat:['armor',3],visual:'shield'},
 {id:'ring',name:'용사의 반지',slot:'ring',cost:240,desc:'치명타 +8%',stat:['crit',.08],visual:'ring'},
 {id:'amulet',name:'흡혈 부적',slot:'amulet',cost:280,desc:'타격 회복 +3',stat:['lifesteal',3],visual:'amulet'}
];
const hero={type:'warrior',pos:new THREE.Vector3(0,0,7),hp:600,maxHp:600,speed:6,damage:58,range:2.8,rate:.42,attack:0,skill:0,crit:.08,power:1,lifesteal:0,obj:null,gear:new THREE.Group()};
const tower={hp:3400,maxHp:3400,armor:0};const enemies=[],projectiles=[],effects=[];const keys=new Set();
let state='menu',wave=1,side=0,spawned=0,spawnClock=.5,gold=500,xp=0,level=1,nextXP=100,inventory=[],equipped={helmet:null,armor:null,gloves:null,boots:null,weapon:null,offhand:null,ring:null,amulet:null};

function syncHud(){ $('wave').textContent='WAVE '+wave;$('direction').textContent=gateNames[side]+' 방향';$('waveCount').textContent=spawned+' / '+enemyTotal();$('heroName').textContent=heroDefs[hero.type].name;$('level').textContent='LV '+level;$('xp').textContent=xp+' / '+nextXP;$('gold').textContent=gold+' G';$('towerText').textContent=Math.ceil(tower.hp)+' / '+tower.maxHp;$('heroHpText').textContent=Math.ceil(hero.hp)+' / '+hero.maxHp;$('towerBar').style.width=Math.max(0,tower.hp/tower.maxHp*100)+'%';$('heroBar').style.width=Math.max(0,hero.hp/hero.maxHp*100)+'%';$('skillText').textContent=hero.skill>0?hero.skill.toFixed(1)+'s':'READY';$('inventoryText').textContent=inventory.length+' / 8';}
function notify(t){$('notice').textContent=t;$('notice').classList.add('show');clearTimeout(window.__note);window.__note=setTimeout(()=>$('notice').classList.remove('show'),1200);}
function enemyTotal(){return 8+wave*2+Math.floor(wave/3)}
function clearWorld(){for(const e of enemies)if(e.obj)scene.remove(e.obj);enemies.length=0;for(const p of projectiles)scene.remove(p.obj);projectiles.length=0;for(const f of effects)scene.remove(f.obj);effects.length=0;}
function gearMesh(item){const g=new THREE.Group(),m=material(0xa48a52);if(item.visual==='sword'){const b=new THREE.Mesh(new THREE.BoxGeometry(.13,1.25,.18),m);b.position.y=.65;const h=new THREE.Mesh(new THREE.BoxGeometry(.55,.1,.12),m);h.position.y=.1;g.add(b,h)}else if(item.visual==='staff'){const b=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,1.7,8),m);b.position.y=.8;const c=new THREE.Mesh(new THREE.SphereGeometry(.15,8,8),new THREE.MeshStandardMaterial({color:0x62dcef,emissive:0x194f50,emissiveIntensity:2}));c.position.y=1.7;g.add(b,c)}else if(item.visual==='bow'){const b=new THREE.Mesh(new THREE.TorusGeometry(.55,.045,6,20,Math.PI*1.35),m);b.rotation.z=Math.PI/2;g.add(b);const s=new THREE.Mesh(new THREE.BoxGeometry(.03,1.2,.03),new THREE.MeshBasicMaterial({color:0xe2d6b2}));s.position.x=.02;g.add(s)}else if(item.visual==='helm'){g.add(new THREE.Mesh(new THREE.SphereGeometry(.48,10,6,0,Math.PI*2,0,Math.PI*.55),m))}else if(item.visual==='armor'){g.add(new THREE.Mesh(new THREE.BoxGeometry(.82,.95,.5),m))}else if(item.visual==='gloves'){const x=new THREE.Mesh(new THREE.BoxGeometry(.18,.32,.2),m);x.position.set(-.5,1,0);g.add(x,x.clone().translateX(1))}else if(item.visual==='boots'){const x=new THREE.Mesh(new THREE.BoxGeometry(.22,.38,.34),m);x.position.set(-.25,.2,.08);g.add(x,x.clone().translateX(.5))}else if(item.visual==='shield'){const s=new THREE.Mesh(new THREE.CylinderGeometry(.45,.45,.12,12),m);s.rotation.z=Math.PI/2;s.position.set(-.65,1.05,.1);g.add(s)}else if(item.visual==='ring'){g.add(new THREE.Mesh(new THREE.TorusGeometry(.12,.035,8,12),new THREE.MeshBasicMaterial({color:0xe8c65d})));g.position.set(.45,.95,.2)}else if(item.visual==='amulet'){g.add(new THREE.Mesh(new THREE.OctahedronGeometry(.14),new THREE.MeshStandardMaterial({color:0x67d9e7,emissive:0x17484a,emissiveIntensity:2})));g.position.set(0,.85,.35)}return g}
function refreshGear(){hero.gear=new THREE.Group();if(hero.obj){hero.obj.add(hero.gear)}for(const k in equipped){const it=equipped[k];if(!it)continue;const g=gearMesh(it);if(k==='helmet')g.position.set(0,1.95,0);if(k==='armor')g.position.set(0,1.15,.08);if(k==='gloves')g.position.set(0,0,0);if(k==='boots')g.position.set(0,-.15,0);if(k==='weapon')g.position.set(.55,.95,.05);if(k==='offhand')g.position.set(0,0,0);hero.gear.add(g)}}
function loadHeroVisual(){if(hero.obj)scene.remove(hero.obj);hero.obj=fallback(heroDefs[hero.type].color,2.2);hero.obj.position.copy(hero.pos);scene.add(hero.obj);loadModel(heroDefs[hero.type].model).then(g=>{const old=hero.obj,o=fit(g,2.35);o.position.copy(hero.pos);scene.add(o);hero.obj=o;refreshGear();if(old)scene.remove(old)}).catch(()=>{refreshGear()})}
function resetRun(){clearWorld();wave=1;side=0;spawned=0;spawnClock=.3;gold=500;xp=0;level=1;nextXP=100;tower.hp=tower.maxHp;inventory=[];for(const k in equipped)equipped[k]=null;const d=heroDefs[hero.type];Object.assign(hero,{hp:d.hp,maxHp:d.hp,speed:d.speed,damage:d.damage,range:d.range,rate:d.rate,attack:0,skill:0,crit:hero.type==='ranger'?.16:.08,power:1,lifesteal:0,pos:new THREE.Vector3(0,0,7)});loadHeroVisual();hideAll();state='play';notify('웨이브 1 · 북쪽 적습');syncHud();}
function startHero(t){hero.type=t;resetRun()}
function spawnEnemy(){if(spawned>=enemyTotal())return;let k='grunt',r=Math.random();if(wave%5===0&&spawned===enemyTotal()-1)k='boss';else if(r<.15)k='runner';else if(r<.30)k='tank';else if(r<.42)k='caster';const d=enemyDefs[k],g=gates[side],e={kind:k,pos:new THREE.Vector3(g.x+(Math.random()-.5)*1.6,0,g.z+(Math.random()-.5)*1.6),hp:d.hp*(1+wave*.12),maxHp:d.hp*(1+wave*.12),speed:d.speed*(1+wave*.008),dmg:d.dmg*(1+wave*.05),gold:d.gold,xp:d.xp,obj:fallback(d.c,d.h),bar:null,dead:false};e.obj.position.copy(e.pos);scene.add(e.obj);makeBar(e);enemies.push(e);spawned++;loadModel(d.model).then(g=>{if(e.dead)return;const old=e.obj,o=fit(g,d.h);o.position.copy(e.pos);scene.add(o);e.obj=o;makeBar(e);if(old)scene.remove(old)}).catch(()=>{})}
function makeBar(e){const bar=new THREE.Group(),bg=new THREE.Mesh(new THREE.PlaneGeometry(1.15,.11),new THREE.MeshBasicMaterial({color:0x271516})),fg=new THREE.Mesh(new THREE.PlaneGeometry(1.1,.075),new THREE.MeshBasicMaterial({color:0x63d678}));fg.position.z=.02;bar.add(bg,fg);bar.position.y=e.kind==='boss'?3.5:2;bar.rotation.x=-.38;bar.userData.fg=fg;e.obj.add(bar);e.bar=bar}
function hit(e,d){if(e.dead)return;e.hp-=d;if(e.hp<=0){e.dead=true;gold+=e.gold;gainXP(e.xp);for(let i=0;i<(e.kind==='boss'?24:6);i++){const p=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,.08),new THREE.MeshBasicMaterial({color:e.kind==='boss'?0xeac05d:0xdce7dc}));p.position.copy(e.pos);scene.add(p);effects.push({obj:p,life:.45,v:new THREE.Vector3((Math.random()-.5)*5,Math.random()*3,(Math.random()-.5)*5),max:.45})}}}
function gainXP(v){xp+=v;if(xp>=nextXP){xp-=nextXP;level++;nextXP=Math.floor(nextXP*1.28);openLevel()}}
function openLevel(){state='level';const b=$('levelChoices');b.replaceChildren();[['공격력 +22',()=>hero.damage+=22],['최대 HP +120',()=>{hero.maxHp+=120;hero.hp+=120}],['이동속도 +0.35',()=>hero.speed+=.35],['치명타 +5%',()=>hero.crit+=.05]].sort(()=>Math.random()-.5).slice(0,3).forEach(a=>{const x=document.createElement('button');x.className='upgradeChoice';x.innerHTML='<b>◆</b><span>'+a[0]+'</span>';x.onclick=()=>{a[1]();hide('levelUp');state='play';syncHud()};b.appendChild(x)});show('levelUp')}
function attack(){if(hero.attack>0)return;let t=null,b=hero.range;for(const e of enemies)if(!e.dead){const d=hero.pos.distanceTo(e.pos);if(d<b){b=d;t=e}}if(!t)return;hero.attack=hero.rate;const dmg=hero.damage*(Math.random()<hero.crit?2:1);if(hero.type==='warrior')hit(t,dmg);else{const o=new THREE.Mesh(new THREE.SphereGeometry(.1,6,6),new THREE.MeshBasicMaterial({color:hero.type==='mage'?0x6de1f3:0xeed36e}));o.position.copy(hero.pos);scene.add(o);projectiles.push({obj:o,target:t,damage:dmg});}if(hero.lifesteal)hero.hp=Math.min(hero.maxHp,hero.hp+hero.lifesteal)}
function useSkill(){if(state!=='play'||hero.skill>0)return;hero.skill=heroDefs[hero.type].skill;const radius=hero.type==='warrior'?4.3:5.7,mult=(hero.type==='warrior'?5.5:hero.type==='mage'?4.8:4.5)*hero.power;for(const e of enemies)if(!e.dead&&hero.pos.distanceTo(e.pos)<radius)hit(e,hero.damage*mult);const ring=new THREE.Mesh(new THREE.RingGeometry(.5,radius,40),new THREE.MeshBasicMaterial({color:hero.type==='mage'?0x62dcef:hero.type==='ranger'?0x7bd46c:0xf0b94c,transparent:true,opacity:.8,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(hero.pos.x,.07,hero.pos.z);scene.add(ring);effects.push({obj:ring,life:.45,max:.45});notify('필살기 발동')}
function move(dt){let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(!x&&!z)return;const v=new THREE.Vector3(x,0,z).normalize().multiplyScalar(hero.speed*dt);hero.pos.add(v);hero.pos.x=THREE.MathUtils.clamp(hero.pos.x,-13.2,13.2);hero.pos.z=THREE.MathUtils.clamp(hero.pos.z,-13.2,13.2);if(hero.obj){hero.obj.position.copy(hero.pos);hero.obj.rotation.y=Math.atan2(v.x,v.z)}}
function update(dt){if(state!=='play')return;hero.attack=Math.max(0,hero.attack-dt);hero.skill=Math.max(0,hero.skill-dt);move(dt);attack();spawnClock-=dt;if(spawnClock<=0){spawnClock=Math.max(.25,.62-wave*.006);spawnEnemy()}for(const p of projectiles){if(!p.target||p.target.dead){p.obj.visible=false;continue}p.obj.position.lerp(new THREE.Vector3(p.target.pos.x,.8,p.target.pos.z),Math.min(1,dt*15));if(p.obj.position.distanceTo(new THREE.Vector3(p.target.pos.x,.8,p.target.pos.z))<.2){hit(p.target,p.damage);p.obj.visible=false}}for(let i=projectiles.length-1;i>=0;i--)if(!projectiles[i].obj.visible){scene.remove(projectiles[i].obj);projectiles.splice(i,1)}let alive=0;for(const e of enemies)if(!e.dead){alive++;const dir=new THREE.Vector3(-e.pos.x,0,-e.pos.z),dist=dir.length();if(dist<2.65)tower.hp-=Math.max(1,e.dmg-tower.armor)*dt;else{dir.normalize();e.pos.addScaledVector(dir,e.speed*dt)}if(e.obj){e.obj.position.copy(e.pos);e.obj.position.y=Math.sin(performance.now()*.006+e.bob)*.03}if(e.bar)e.bar.userData.fg.scale.x=Math.max(.02,e.hp/e.max)}}for(const f of effects){f.life-=dt;if(f.v){f.obj.position.addScaledVector(f.v,dt);f.v.multiplyScalar(.91)}if(f.obj.scale)f.obj.scale.setScalar(1+(f.max-f.life)*1.6)}for(let i=effects.length-1;i>=0;i--)if(effects[i].life<=0){scene.remove(effects[i].obj);effects.splice(i,1)}for(let i=enemies.length-1;i>=0;i--)if(enemies[i].dead){scene.remove(enemies[i].obj);enemies.splice(i,1)}if(spawned>=enemyTotal()&&alive===0){side=(side+1)%4;spawned=0;spawnClock=.55;if(side===0){wave++;gold+=100;tower.hp=Math.min(tower.maxHp,tower.hp+160);notify('웨이브 '+wave+' 시작')}else notify(gateNames[side]+' 방향 적습')}if(tower.hp<=0){tower.hp=0;state='over';$('overDetail').textContent=`웨이브 ${wave} · 레벨 ${level} · ${gold} G · ${heroDefs[hero.type].name}`;show('gameover')}syncHud()}

function renderInventory(){const b=$('inventoryGrid');b.replaceChildren();for(let i=0;i<8;i++){const id=inventory[i],x=document.createElement('button');x.className='invSlot';if(id){const it=shopItems.find(a=>a.id===id);x.innerHTML='<strong>'+it.name+'</strong><small>'+slots[it.slot]+'</small>';x.onclick=()=>equipItem(i)}else{x.innerHTML='<span>빈 슬롯</span>';x.disabled=true}b.appendChild(x)}}
function renderEquipment(){const center=$('equipCharacter');center.textContent=heroDefs[hero.type].name;const grid=$('equipSlots');grid.replaceChildren();Object.entries(slots).forEach(([k,label])=>{const b=document.createElement('button');b.className='equipSlot';const it=equipped[k];b.innerHTML='<b>'+label+'</b><span>'+ (it?it.name:'비어있음')+'</span>';b.onclick=()=>{if(!it)return;inventory.push(it.id);equipped[k]=null;rebuildStats();refreshGear();renderEquipment();renderInventory();syncHud()};grid.appendChild(b)});$('equipStats').innerHTML=`공격력 <b>${Math.round(hero.damage)}</b> · HP <b>${Math.round(hero.hp)}/${hero.maxHp}</b><br>이동속도 <b>${hero.speed.toFixed(1)}</b> · 치명타 <b>${Math.round(hero.crit*100)}%</b> · 스킬배율 <b>${hero.power.toFixed(2)}x</b>`}
function rebuildStats(){const d=heroDefs[hero.type];Object.assign(hero,{maxHp:d.hp,speed:d.speed,damage:d.damage,range:d.range,rate:d.rate,crit:hero.type==='ranger'?.16:.08,power:1,lifesteal:0});for(const k in equipped){const it=equipped[k];if(!it)continue;if(it.stat[0]==='maxHp')hero.maxHp+=it.stat[1];else hero[it.stat[0]]+=it.stat[1];}hero.hp=Math.min(hero.maxHp,hero.hp);}
function equipItem(i){const id=inventory[i],it=shopItems.find(a=>a.id===id);if(!it)return;const old=equipped[it.slot];if(old){inventory[i]=old.id}else inventory.splice(i,1);equipped[it.slot]=it;rebuildStats();refreshGear();renderEquipment();renderInventory();syncHud();notify(it.name+' 장착')}
function renderShop(){const b=$('shopItems');b.replaceChildren();$('shopGold').textContent=gold+' G';shopItems.forEach(it=>{const x=document.createElement('button');x.className='shopItem';x.innerHTML=`<strong>${it.name}</strong><span>${slots[it.slot]} · ${it.desc}</span><em>${it.cost} G</em>`;x.onclick=()=>{if(inventory.length>=8){notify('인벤토리가 가득 찼습니다');return}if(gold<it.cost){notify('골드가 부족합니다');return}gold-=it.cost;inventory.push(it.id);renderShop();renderInventory();syncHud();notify(it.name+' 획득 · 인벤토리로 이동')};b.appendChild(x)})}
function toggleShop(){if(state==='menu'||state==='over'||state==='level'||state==='equipment')return;state=state==='shop'?'play':'shop';$('shop').classList.toggle('hidden',state!=='shop');if(state==='shop')renderShop()}
function toggleEquipment(){if(state==='menu'||state==='over'||state==='level'||state==='shop')return;state=state==='equipment'?'play':'equipment';$('equipment').classList.toggle('hidden',state!=='equipment');if(state==='equipment'){renderEquipment();renderInventory()}}

addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','q','i','e'].includes(k))e.preventDefault();if(k==='q')useSkill();if(k==='i')toggleShop();if(k==='e')toggleEquipment();if(k==='escape'){if(state==='play'){state='pause';show('pause')}else if(state==='pause'){state='play';hide('pause')}else if(state==='shop'){toggleShop()}else if(state==='equipment'){toggleEquipment()}}});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
$('startBtn').onclick=()=>{hide('start');show('heroSelect')};$('warriorBtn').onclick=()=>startHero('warrior');$('mageBtn').onclick=()=>startHero('mage');$('rangerBtn').onclick=()=>startHero('ranger');$('shopBtn').onclick=toggleShop;$('equipBtn').onclick=toggleEquipment;$('shopClose').onclick=toggleShop;$('equipClose').onclick=toggleEquipment;$('resumeBtn').onclick=()=>{state='play';hide('pause')};$('restartBtn').onclick=()=>{state='menu';hideAll();show('start')};
function resize(){renderer.setSize(innerWidth,innerHeight,false);const a=Math.max(.55,innerWidth/innerHeight),h=10,w=h*a;camera.left=-w;camera.right=w;camera.top=h;camera.bottom=-h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
for(const k of Object.keys(models))loadModel(k).catch(()=>{});
let last=performance.now();function animate(now){const dt=Math.min(.033,Math.max(0,(now-last)/1000));last=now;update(dt);crystal.rotation.y+=dt*1.2;renderer.render(scene,camera);requestAnimationFrame(animate)}requestAnimationFrame(animate);
