(()=>{
'use strict';
const root=document.getElementById('canvas');
const c=document.createElement('canvas'); c.id='gameCanvas'; root.replaceChildren(c);
const ctx=c.getContext('2d'); ctx.imageSmoothingEnabled=false;
const W=960,H=720;
let state='menu',last=0,time=0,wave=1,gold=150,level=1,xp=0,nextXp=80,side=0,spawnLeft=0,spawnTimer=0,skillTimer=0;
const keys=new Set(),enemies=[],particles=[];
const hero={x:480,y:560,hp:360,maxHp:360,speed:240,damage:38,attack:0,skill:0,dir:0};
const tower={x:480,y:360,hp:1500,maxHp:1500};
const sides=[{x:480,y:-20},{x:980,y:360},{x:480,y:740},{x:-20,y:360}];
const names=['북','동','남','서'];
const types={grunt:{hp:45,spd:55,dmg:10,gold:6,xp:10,r:14},runner:{hp:30,spd:95,dmg:7,gold:8,xp:14,r:11},tank:{hp:180,spd:32,dmg:22,gold:18,xp:30,r:19},boss:{hp:1800,spd:25,dmg:50,gold:180,xp:300,r:30}};
function resize(){const r=root.getBoundingClientRect();const s=Math.min(r.width/W,r.height/H)||1;c.width=W;c.height=H;c.style.width=W*s+'px';c.style.height=H*s+'px'}
addEventListener('resize',resize); resize();
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase()); if(e.key.toLowerCase()==='q')useSkill(); if(e.key==='Escape'&&state==='play')state='pause'});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function reset(){wave=1;gold=150;level=1;xp=0;nextXp=80;side=0;spawnLeft=0;spawnTimer=0;skillTimer=0;enemies.length=0;particles.length=0;hero.x=480;hero.y=560;hero.maxHp=360;hero.hp=360;hero.speed=240;hero.damage=38;hero.attack=0;hero.skill=0;tower.hp=tower.maxHp;state='play';startWave();hideAll()}
function hideAll(){for(const id of ['start','gameover','pause','upgrade']){const e=document.getElementById(id);if(e)e.classList.add('hidden')}}
function startWave(){spawnLeft=8+wave*3;spawnTimer=.2;document.getElementById('waveText').textContent=`WAVE ${wave} · ${names[side]} 방향`}
function choose(){reset()}
function spawn(){if(spawnLeft<=0)return;let k='grunt',r=Math.random();if(wave%5===0&&spawnLeft===1&&side===3)k='boss';else if(r<.16)k='runner';else if(r<.29)k='tank';const z=types[k],p=sides[side];const e={kind:k,x:p.x+(Math.random()-.5)*50,y:p.y+(Math.random()-.5)*50,hp:z.hp*(1+wave*.11),max:z.hp*(1+wave*.11),spd:z.spd*(1+wave*.006),dmg:z.dmg*(1+wave*.05),r:z.r,hit:0};enemies.push(e);spawnLeft--;spawnTimer=Math.max(.22,.5-wave*.008)}
function gain(v){xp+=v;while(xp>=nextXp){xp-=nextXp;level++;nextXp=Math.floor(nextXp*1.25);openUpgrade();return}}
function kill(e){if(e.dead)return;e.dead=true;const z=types[e.kind];gold+=z.gold;gain(z.xp);for(let i=0;i<10;i++)particles.push({x:e.x,y:e.y,vx:(Math.random()-.5)*150,vy:(Math.random()-.5)*150,life:.5});}
function attack(){if(hero.attack>0)return;let range=125,best=null,bd=range;for(const e of enemies)if(!e.dead){const d=Math.hypot(e.x-hero.x,e.y-hero.y);if(d<bd){bd=d;best=e}}if(!best)return;hero.attack=.38;best.hp-=hero.damage; if(best.hp<=0)kill(best)}
function useSkill(){if(state!=='play'||hero.skill>0)return;hero.skill=6;for(const e of enemies)if(!e.dead&&Math.hypot(e.x-hero.x,e.y-hero.y)<190){e.hp-=hero.damage*4;if(e.hp<=0)kill(e)}for(let i=0;i<30;i++)particles.push({x:hero.x,y:hero.y,vx:(Math.random()-.5)*300,vy:(Math.random()-.5)*300,life:.7})}
function move(dt){let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(dx||dy){const n=Math.hypot(dx,dy);hero.x=Math.max(25,Math.min(935,hero.x+dx/n*hero.speed*dt));hero.y=Math.max(25,Math.min(695,hero.y+dy/n*hero.speed*dt))}}
function update(dt){if(state!=='play')return;hero.attack=Math.max(0,hero.attack-dt);hero.skill=Math.max(0,hero.skill-dt);move(dt);attack();if(spawnLeft>0){spawnTimer-=dt;if(spawnTimer<=0)spawn()}for(const e of enemies)if(!e.dead){const dx=tower.x-e.x,dy=tower.y-e.y,d=Math.hypot(dx,dy)||1;if(d<62)tower.hp-=Math.max(1,e.dmg)*dt;else{e.x+=dx/d*e.spd*dt;e.y+=dy/d*e.spd*dt}}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.92;p.vy*=.92;p.life-=dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(let i=enemies.length-1;i>=0;i--)if(enemies[i].dead)enemies.splice(i,1);if(spawnLeft===0&&enemies.length===0){side=(side+1)%4;if(side===0){wave++;gold+=60;tower.hp=Math.min(tower.maxHp,tower.hp+80)}startWave()}if(tower.hp<=0){tower.hp=0;state='over';document.getElementById('gameoverDetail').textContent=`WAVE ${wave} · LV ${level} · 획득 골드 ${gold}G`;document.getElementById('gameover').classList.remove('hidden')}}
function draw(){ctx.fillStyle='#142019';ctx.fillRect(0,0,W,H);for(let y=0;y<H;y+=32)for(let x=0;x<W;x+=32){ctx.fillStyle=((x/32+y/32)%2===0)?'#1c2b20':'#203124';ctx.fillRect(x,y,32,32)}ctx.fillStyle='#304b35';ctx.beginPath();ctx.arc(480,360,155,0,Math.PI*2);ctx.fill();drawTower();for(const e of enemies)drawEnemy(e);drawHero();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/.7);ctx.fillStyle='#f4d36a';ctx.fillRect(p.x|0,p.y|0,5,5);ctx.globalAlpha=1}ctx.fillStyle='#09120e';ctx.fillRect(12,12,310,84);ctx.fillStyle='#f4d36a';ctx.font='bold 20px monospace';ctx.fillText(`WAVE ${wave}`,26,37);ctx.fillStyle='#c4ddd0';ctx.font='13px monospace';ctx.fillText(`${names[side]} 방향  ·  남은 적 ${spawnLeft+enemies.length}`,26,61);ctx.fillText(`LV ${level}  XP ${xp}/${nextXp}  GOLD ${gold}`,26,82);ctx.fillStyle='#09120e';ctx.fillRect(690,12,258,55);ctx.fillStyle='#d8eee5';ctx.fillText(`수호탑 HP`,706,33);bar(706,42,220,12,tower.hp/tower.maxHp,'#2a1919','#61d58c');ctx.fillStyle='#d8eee5';ctx.fillText(`Q 스킬 ${hero.skill>0?hero.skill.toFixed(1)+'s':'READY'}`,706,61)}
function bar(x,y,w,h,p,bg,fg){ctx.fillStyle=bg;ctx.fillRect(x,y,w,h);ctx.fillStyle=fg;ctx.fillRect(x+2,y+2,(w-4)*Math.max(0,Math.min(1,p)),h-4)}
function drawTower(){ctx.fillStyle='#18251d';ctx.fillRect(390,405,180,28);ctx.fillStyle='#637968';ctx.fillRect(405,295,150,120);ctx.fillStyle='#3b5140';ctx.fillRect(430,315,100,100);ctx.fillStyle='#738b76';ctx.fillRect(410,275,35,55);ctx.fillRect(515,275,35,55);ctx.fillStyle='#8c5c43';ctx.beginPath();ctx.moveTo(395,295);ctx.lineTo(480,240);ctx.lineTo(565,295);ctx.fill();ctx.fillStyle='#45d4d4';ctx.fillRect(462,350,36,65);ctx.fillStyle='#20291f';ctx.fillRect(445,385,70,30);bar(382,220,196,14,tower.hp/tower.maxHp,'#291919','#61d58c');ctx.fillStyle='#f1e3b2';ctx.font='bold 15px monospace';ctx.textAlign='center';ctx.fillText('수호탑',480,205);ctx.textAlign='left'}
function drawHero(){ctx.fillStyle='#101815';ctx.fillRect(hero.x-15,hero.y+17,30,7);ctx.fillStyle='#d6b08c';ctx.fillRect(hero.x-10,hero.y-25,20,20);ctx.fillStyle='#355b75';ctx.fillRect(hero.x-13,hero.y-5,26,27);ctx.fillStyle='#b98a45';ctx.fillRect(hero.x-18,hero.y-8,6,30);ctx.fillStyle='#e2c15b';ctx.fillRect(hero.x+12,hero.y-10,8,34)}
function drawEnemy(e){const z=types[e.kind];ctx.fillStyle=e.kind==='boss'?'#b94141':e.kind==='tank'?'#617c5d':e.kind==='runner'?'#b6a54f':'#9b7658';ctx.fillRect(e.x-z.r,e.y-z.r,e.r*2,e.r*2);ctx.fillStyle='#1b1410';ctx.fillRect(e.x-z.r*.5,e.y-z.r*.2,5,5);ctx.fillRect(e.x+z.r*.2,e.y-z.r*.2,5,5);bar(e.x-z.r,e.y-z.r-9,z.r*2,5,e.hp/e.max,'#2b1717','#d95f61')}
function openUpgrade(){state='upgrade';const box=document.getElementById('upgradeChoices');box.replaceChildren();[['공격력','공격력 +15',()=>hero.damage+=15],['체력','최대 HP +80',()=>{hero.maxHp+=80;hero.hp=hero.maxHp}],['이동속도','이동속도 +30',()=>hero.speed+=30]].forEach(u=>{const b=document.createElement('button');b.innerHTML=`<b>${u[0]}</b><small>${u[1]}</small>`;b.onclick=()=>{u[2]();document.getElementById('upgrade').classList.add('hidden');state='play'};box.appendChild(b)})}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;time+=dt;update(dt);draw();requestAnimationFrame(loop)}
document.getElementById('startBtn').onclick=choose;document.getElementById('restartBtn').onclick=choose;document.getElementById('resumeBtn').onclick=()=>{document.getElementById('pause').classList.add('hidden');state='play'};
hideAll();document.getElementById('start').classList.remove('hidden');requestAnimationFrame(loop);
})();